server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: stanislav
    password: test123
    virtual-host: plex_virtual_host
  datasource:
    url: jdbc:sqlite:/Users/stanislavarabov/Downloads/5.db
    driverClassName: org.sqlite.JDBC
  jpa:
    hibernate:
      show-sql: true
      database-platform: org.hibernate.community.dialect.SQLiteDialect